### ISSUE TITLE
PS3 Move naigation controller

### ISSUE THREAD

**Issue by mhm203** [user-none/sixaxispairer#8]
Has anyone been able to get this to work with the PS3 move navigation controller, when i try it just brings up "Could not find SixAxis controller" does this work different to the standard controllers in terms of setting the mac address?

**Comment by user-none** [comment]
Can you plug in the device and provide the output of `lsusb -v`?

**Comment by mhm203** [comment]
USB 3.1 Bus:

      Host Controller Driver: AppleT8103USBXHCI

    USB 3.1 Bus:

      Host Controller Driver: AppleT8103USBXHCI

        Navigation Controller:

          Product ID: 0x042f
          Vendor ID: 0x054c  (Sony Corporation)
          Version: 1.00
          Speed: Up to 12 Mb/s
          Manufacturer: Sony
          Location ID: 0x00100000 / 1
          Current Available (mA): 500
          Current Required (mA): 500
          Extra Operating Current (mA): 0

**Comment by user-none** [comment]
It's a difference product id than the standard six axis. Reading about it, the device should behave the same way as the six axis for pairing. I created the ps3-move branch which will use the id for the move controller instead of the six axis id. Can you build from that branch and try?

I don't have to the move controller so I can't test. If it works then I can make changes to support both of them in main.

**Comment by mhm203** [comment]
worked perfectly amazing work thanks

**Comment by user-none** [comment]
Addition of the ps3 move motion controller added to main in [69c2f83].
